PREFIX wdt: <https://kg-ipclimatec-reports.wikibase.cloud/prop/direct/>
PREFIX wd:  <https://kg-ipclimatec-reports.wikibase.cloud/entity/>
PREFIX p:   <https://kg-ipclimatec-reports.wikibase.cloud/prop/>
PREFIX pq:  <https://kg-ipclimatec-reports.wikibase.cloud/prop/qualifier/>
PREFIX ps:  <https://kg-ipclimatec-reports.wikibase.cloud/prop/statement/>

SELECT DISTINCT ?fact ?factLabel (GROUP_CONCAT(?value_string; separator=", ") as ?confidences) WHERE {
  VALUES ?section { wd:Q49 }
  ?section p:P3 ?factStatement .
  BIND (?section AS ?fact)
  ?factStatement ps:P3 ?factLabel .
  ?factStatement pq:P5 ?confidence .
  ?confidence rdfs:label ?value_string . 
  FILTER (LANG(?value_string) = 'en')
} GROUP BY ?fact ?factLabel
